Feature/lesson1
olya1998/project pull request #1
Opened 2022-06-01 15:14 UTC by olya1998

Hey Boss, please take a look at my PR

2022-06-01 15:16 UTC, setysoft requested changes

2022-06-01 15:16 UTC, setysoft commented on src/index.html
> +    <title>Pulse 123</title>
What the hell is this?

2022-06-02 18:17 UTC, setysoft approved these changes

2022-06-02 18:20 UTC, merged

2022-06-03 13:01 UTC, olya1998 commented on src/index.html
> +    <title>Pulse 123</title>
please take a look